version: '3'

networks:
  project-network:
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - project-network

  kafka_broker1:
    image: bitnami/kafka:latest
    container_name: kafka_broker1
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - project-network

  init-kafka:
    image: confluentinc/cp-kafka:6.1.1
    networks:
      - project-network
    depends_on:
      - kafka_broker1
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka_broker1:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka_broker1:9092 --create --if-not-exists --topic RootDomainVisitsTopic --replication-factor 1 --partitions 3
      
      # Technical topics
      kafka-topics --bootstrap-server kafka_broker1:9092 --create --if-not-exists --topic statistics-aggregator-visits-count-changelog --replication-factor 1 --partitions 3
      
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka_broker1:9092 --list
      "

  generator:
    build:
      context: ./generator
    networks:
      - project-network
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 30
        # Run the client code
        python -u main.py

  statistics-aggregator:
    build:
      context: ./statistics-aggregator
    networks:
      - project-network
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        # Run the client code
        python -m faust -A kafka_streams worker -l info
